version: '3.4'
services:
  app:
    image: app_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - DATABASE_URL=${DATABASE_URL}
    depends_on: 
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  db_data: